// File generated by FlutterFire CLI.
// To update, run: firebase flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for different platforms.
///
/// NOTE: These options are generated using your project ID `wetrack-fc09f`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyXXXXXXXXXXXXXXXXXX-web', // Placeholder: Update with your actual Web API Key
    appId: '1:421690155245:web:45ba18dd9897a1d1786ce4',
    messagingSenderId: '421690155245',
    projectId: 'wetrack-fc09f',
    authDomain: 'wetrack-fc09f.firebaseapp.com',
    storageBucket: 'wetrack-fc09f.appspot.com',
    measurementId: 'G-XXXXXXXXXX', // Placeholder
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyXXXXXXXXXXXXXXXXXX-android', // Placeholder: Update with your actual Android API Key
    appId: '1:421690155245:android:f1ab63bc9e6ba91a786ce4',
    messagingSenderId: '421690155245',
    projectId: 'wetrack-fc09f',
    storageBucket: 'wetrack-fc09f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyXXXXXXXXXXXXXXXXXX-ios', // Placeholder: Update with your actual iOS API Key
    appId: '1:421690155245:ios:d5a4906bf3aacc2f786ce4',
    messagingSenderId: '421690155245',
    projectId: 'wetrack-fc09f',
    storageBucket: 'wetrack-fc09f.appspot.com',
    iosClientId:
        '421690155245-xxxxxxxxxxxx.apps.googleusercontent.com', // Placeholder
    iosBundleId: 'com.example.wetrack', // Replace with your bundle ID
  );
}
